-- Create AuditLog Table

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    ActionDate DATE,
    ActionDescription VARCHAR2(200),
    PRIMARY KEY (AuditID)
);

-- Scenario 1:
-- Update LastModified Automatically

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- Scenario 2:
-- Log Transactions into AuditLog

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (
        TransactionID,
        AccountID,
        ActionDate,
        ActionDescription
    )
    VALUES
    (
        :NEW.TransactionID,
        :NEW.AccountID,
        SYSDATE,
        'Transaction Inserted'
    );
END;
/

-- Scenario 3:
-- Validate Deposits and Withdrawals

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_Balance NUMBER;
BEGIN

    IF UPPER(:NEW.TransactionType) = 'DEPOSIT' THEN

        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(
                -20010,
                'Deposit amount must be greater than zero.'
            );
        END IF;

    ELSIF UPPER(:NEW.TransactionType) = 'WITHDRAWAL' THEN

        SELECT Balance
        INTO v_Balance
        FROM Accounts
        WHERE AccountID = :NEW.AccountID;

        IF :NEW.Amount > v_Balance THEN
            RAISE_APPLICATION_ERROR(
                -20011,
                'Withdrawal exceeds available balance.'
            );
        END IF;

    END IF;

END;
/

-- TESTING SCENARIO 1

UPDATE Customers
SET Balance = Balance + 100
WHERE CustomerID = 1;

SELECT CustomerID,
       Name,
       LastModified
FROM Customers
WHERE CustomerID = 1;

-- TESTING SCENARIO 2

INSERT INTO Transactions
(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES
(
    100,
    1,
    SYSDATE,
    200,
    'Deposit'
);

SELECT *
FROM AuditLog;

-- TESTING SCENARIO 3

-- Valid Deposit

INSERT INTO Transactions
(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES
(
    101,
    1,
    SYSDATE,
    500,
    'Deposit'
);

-- Valid Withdrawal

INSERT INTO Transactions
(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES
(
    102,
    1,
    SYSDATE,
    100,
    'Withdrawal'
);

-- Invalid Withdrawal
-- Uncomment to test error

/*
INSERT INTO Transactions
(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES
(
    103,
    1,
    SYSDATE,
    999999,
    'Withdrawal'
);
*/

-- VERIFY RESULTS

SELECT * FROM AuditLog;

SELECT * FROM Transactions;

SELECT AccountID,
       Balance
FROM Accounts;