CREATE DATABASE hibernate_demo;

USE hibernate_demo;

CREATE TABLE EMPLOYEE (

    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,

    FIRST_NAME VARCHAR(50),

    LAST_NAME VARCHAR(50),

    SALARY INT

);

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, SALARY)
VALUES('Robert','King',50000);

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, SALARY)
VALUES('John','David',45000);

SELECT * FROM EMPLOYEE;